---
- hosts: sr_hosts
  remote_user: root
  vars_files:
  - ../../conf/setup_vars.yml
  tasks:
  - name: decompress all SR Software packages
    unarchive:
      src: "{{ starrocks_ansible_home}}/pack/StarRocks-2.2.0.tar.gz"
      dest: "{{ sr_dest_path }}"
      copy: yes
  
  - name: mkdir meta 
    file: 
      path: "{{ metadata_path }}"
      state: directory

  - name: mkdir storage
    file: 
      path: "{{ item }}"
      state: directory
    with_items: "{{ storage_root_path.split(';') }}"


- hosts: sr_master
  remote_user: root
  vars_files:
    - ../../conf/setup_vars.yml
  tasks:
  - name: alter fe_priority_networks
    lineinfile:
      dest: "{{ sr_home }}/fe/conf/fe.conf"
      insertafter: "# priority_networks"
      line: "priority_networks = {{ be_priority_networks }}\n"

  - name: alter fe http_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "8030"
      replace: "{{ http_port }}"

  - name: alter fe rpc_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9020"
      replace: "{{ rpc_port }}"

  - name: alter fe query_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9030"
      replace: "{{ query_port }}"

  - name: alter fe edit_log_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9010"
      replace: "{{ edit_log_port }}"

  - name: alter fe metadir
    lineinfile:
      dest: "{{ sr_home }}/fe/conf/fe.conf"
      insertafter: "# store metadata"
      line: "meta_dir = {{ metadata_path }}\n"

  - name: get java_home
    shell: cat /etc/profile |grep 'export JAVA_HOME' | awk -F 'export' '{print $2}'
    register: java_home
    ignore_errors: true

  - name: java home is not ok
    lineinfile:
      path: "{{ sr_home }}/fe/bin/start_fe.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home.stdout }}"

  - name: sleep
    shell: sleep 3

  - name: start master
    shell:
      cmd:
        "/bin/bash {{ sr_home }}/fe/bin/start_fe.sh --daemon"


- hosts: sr_frontends
  remote_user: root
  vars_files:
    - ../../conf/setup_vars.yml
  tasks:
  - name: alter fe_priority_networks
    lineinfile:
      dest: "{{ sr_home }}/fe/conf/fe.conf"
      insertafter: "# priority_networks"
      line: "priority_networks = {{ fe_priority_networks }}\n"

  - name: alter fe http_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "8030"
      replace: "{{ http_port }}"

  - name: alter fe rpc_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9020"
      replace: "{{ rpc_port }}"

  - name: alter fe query_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9030"
      replace: "{{ query_port }}"

  - name: alter fe edit_log_port
    replace:
      path: "{{ sr_home }}/fe/conf/fe.conf"
      regexp: "9010"
      replace: "{{ edit_log_port }}"

  - name: alter fe metadir
    lineinfile:
      dest: "{{ sr_home }}/fe/conf/fe.conf"
      insertafter: "# store metadata"
      line: "meta_dir = {{ metadata_path }}\n"

  - name: get java_home
    shell: cat /etc/profile |grep 'export JAVA_HOME' | awk -F 'export' '{print $2}'
    register: java_home
    ignore_errors: true

  - name: java home is not ok
    lineinfile:
      path: "{{ sr_home }}/fe/bin/start_fe.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home.stdout }}"

  - name: start follower
    shell:
      cmd: "/bin/sh {{ sr_home }}/fe/bin/start_fe.sh --helper {{ master }}:{{ edit_log_port }} --daemon"


- hosts: sr_backends
  remote_user: root
  vars_files:
  - ../../conf/setup_vars.yml
  tasks:
  - name: alter be_priority_networks
    lineinfile:
      dest: "{{ sr_home }}/be/conf/be.conf"
      insertafter: "# priority_networks"
      line: "priority_networks = {{ be_priority_networks }}\n"

  - name: alter be be_port
    replace:
      path: "{{ sr_home }}/be/conf/be.conf"
      regexp: "9060"
      replace: "{{ be_port }}"

  - name: alter be webserver_port
    replace:
      path: "{{ sr_home }}/be/conf/be.conf"
      regexp: "8040"
      replace: "{{ webserver_port }}"

  - name: alter be heartbeat_service_port
    replace:
      path: "{{ sr_home }}/be/conf/be.conf"
      regexp: "9050"
      replace: "{{ heartbeat_service_port }}"

  - name: alter be brpc_port
    replace:
      path: "{{ sr_home }}/be/conf/be.conf"
      regexp: "8060"
      replace: "{{ brpc_port }}"

  - name: alter be metadir
    lineinfile:
      dest: "{{ sr_home }}/be/conf/be.conf"
      insertafter: "# storage_root_path"
      line: "storage_root_path = {{ storage_root_path }}\n"

  - name: start all backends
    shell:
      cmd: "/bin/sh {{ sr_home }}/be/bin/start_be.sh --daemon"


- hosts: sr_brokers
  remote_user: root
  vars_files:
  - ../../conf/setup_vars.yml
  tasks:
  - name: get java_home
    shell: cat /etc/profile |grep 'export JAVA_HOME' | awk -F 'export' '{print $2}' | awk -F '=' '{print $2}'
    register: java_home
    ignore_errors: true

  - name: java home is not ok
    lineinfile:
      path: "{{ sr_home }}/apache_hdfs_broker/bin/start_broker.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home.stdout }}"

  - name: start all brokers
    shell:
      cmd: "/bin/sh {{ sr_home }}/apache_hdfs_broker/bin/start_broker.sh --daemon"
- hosts: sr_master
  remote_user: root
  vars_files:
  - ../../conf/setup_vars.yml
  tasks:
  - name: sleep 30 s
    shell: sleep 30

  - name: add folower
    shell:
      cmd: echo "alter system add follower \"{{ item }}:{{ edit_log_port }}\";" | mysql -h{{ master }} -P{{ query_port }} -uroot
    with_items: "{{follower}}"

  - name: add backends
    shell:
      cmd: echo "alter system add BACKEND \"{{ item }}:{{ heartbeat_service_port }}\";" | mysql -h{{ master }} -P{{ query_port }} -uroot
    with_items: "{{backends}}"

  - name: add brokres
    shell:
      cmd: echo "alter system add broker broker1  \"{{ item }}:{{ broker_ipc_port }}\";" | mysql -h{{ master }} -P{{ query_port }} -uroot
    with_items: "{{brokers}}"


- hosts: sr_master
  remote_user: root
  vars_files:
  - ../../conf/setup_vars.yml
  tasks:
  - name: sleep 30 s
    shell: sleep 30

  - name: copy sql to dest
    copy:
      src: "{{ starrocks_ansible_home}}/files/sql/pile_rocks.sql"
      dest: "{{ sr_home }}/fe"

  - name: alter sql password and ip
    replace:
      path: "{{ sr_home }}/fe/pile_rocks.sql"
      regexp: "192.168.0.171"
      replace: "{{ e_mysql_ip }}"

  - name: alter sql password and ip
    replace:
      path: "{{ sr_home }}/fe/pile_rocks.sql"
      regexp: "\"\""
      replace: "\"{{ e_mysql_password }}\""

  - name: echo sql to doris
    shell: echo "source {{ sr_home }}/fe/pile_rocks.sql" | mysql -h{{ master }} -P{{ query_port }} -uroot

  - name: alter password
    shell: echo "SET PASSWORD = PASSWORD({{ 'sr_password' }});" | mysql -h{{ master }} -P{{ query_port }} -uroot
